- name: Set up WSO2 API Manager environment
  hosts: all
  tasks:
    - name: Stop and disable WSO2 API Manager service
      systemd:
        name: wso2am
        state: stopped
        enabled: yes
      become: yes