- name: Set up WSO2 API Manager environment
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - openjdk-11-jdk
          - maven
          - ant
        state: present

    - name: Set Java 11 as default
      shell: |
        update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
        update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
        update-alternatives --set jar /usr/lib/jvm/java-11-openjdk-amd64/bin/jar
        update-alternatives --set javadoc /usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc
        update-alternatives --set javaws /usr/lib/jvm/java-11-openjdk-amd64/bin/javaws
        update-alternatives --set java_sdk /usr/lib/jvm/java-11-openjdk-amd64
        update-alternatives --set java_sdk_man /usr/lib/jvm/java-11-openjdk-amd64/man
        update-alternatives --set java_sdk_doc /usr/lib/jvm/java-11-openjdk-amd64/jre/man

    - name: Copy WSO2 API Manager from local file
      copy:
        src: ~/Downloads/wso2am-4.2.0.zip
        dest: /tmp/wso2am-4.2.0.zip
        remote_src: yes

    - name: Unzip WSO2 API Manager
      unarchive:
        src: /tmp/wso2am-4.2.0.zip
        dest: /opt
        remote_src: yes

    - name: Set up WSO2 API Manager
      block:
        - name: Create WSO2 API Manager directories
          file:
            path:
              - /opt/wso2am-4.2.0/repository/deployment/server
              - /opt/wso2am-4.2.0/repository/logs
            state: directory
            owner: wso2user
            group: wso2user

        - name: Set up WSO2 API Manager user
          user:
            name: wso2user
            state: present
            system: yes
            create_home: yes
            shell: /bin/bash

        - name: Set up WSO2 API Manager service
          systemd:
            name: wso2am
            enabled: yes
            state: started
            unit:
              description: WSO2 API Manager
              after: network.target
              wanted_by: multi-user.target
              service:
                type: simple
                user: wso2user
                group: wso2user
                exec_start: /opt/wso2am-4.2.0/bin/wso2server.sh start
                exec_stop: /opt/wso2am-4.2.0/bin/wso2server.sh stop
                pid_file: /opt/wso2am-4.2.0/repository/logs/wso2carbon.pid
                environment_file: /opt/wso2am-4.2.0/bin/wso2server.sh
                environment:
                  - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd