- name: Set up WSO2 API Manager environment
  hosts: all
  tasks:
    - name: Start and enable WSO2 API Manager service
      systemd:
        name: wso2gw
        state: started
        enabled: yes
      become: yes