- name: create database
  hosts: all 
  vars_files:
    - vars.yaml 
  tasks:
    - name: create database according to vars specs
      become: true
      become_user: postgres
      postgresql_db: name={{ db_name }} template='template0' state=present
    - name: create user for that database
      become: true
      become_user: postgres
      postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL state=present
    - name: remove superuser permission from created user
      become: true
      become_user: postgres
      postgresql_user: name={{ db_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB state=present
