- name: Install dependencies
  hosts: idcloudhost
  tasks:
    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        update_cache: true
        state: latest
      loop:
        - bash
        - ssh
        - libssl-dev
        - libssl-doc
        - acl
      become: true
    - name: Install PostgreSQL and related packages
      apt:
        name: "{{ item }}"
        update_cache: true
        state: latest
      loop:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python3-psycopg2
      become: true
    - name: Ensure PostgreSQL service is started and enabled
      service:
        name: postgresql
        state: started
        enabled: yes
      become: true
