- name: create table
  hosts: all 
  vars_files:
    - vars.yaml
  tasks:
    - name: create dummy table
      become: true
      become_user: postgres
      community.postgresql.postgresql_table:
        db: "{{ db_name }}"
        owner: "{{ db_user }}"
        name: test
        columns:
          - id bigserial PRIMARY KEY NOT NULL
          - message TEXT NOT NULL
